meta_product_name: "GoClimb"
meta_title: "Curated routes to improve your climbing journey - Find your next challenge"
meta_description: "GoGlimb curates routes for you based on your location, skill set and prefered style so you can optimize your climbing trips in a fun and riskless way"
meta_image: "cover.png" # should exist in `app/assets/images/`
